version: '3.3'
services:
  app:
    container_name: node
    image: fminotto/node-web-app
    depends_on: 
      - mysql
    working_dir: /usr/src/app
    volumes:
      - .:/application
    links:
      - mysql
    ports:
      - "44340:44340"
    networks: 
      - backend    
    env_file: ./.env.docker
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=helpper
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=sysdba

  mysql:
    env_file: ./.env
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    networks:
      - backend      
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=helpper
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=sysdba
networks: 
  backend: